STOCKROOM_UNITS = (
    ('%', '% percent'),
    ('mm', 'millimeters'),
    ('cm', 'centimeters'),
    ('m', 'meters'),
    ('km', 'kilometers'),
    ('in', 'inches'),
    ('ft', 'feet'),
    ('yd', 'yards'),
    ('mi', 'miles'),
    ('sq mm', 'square millimeters'),
    ('sq cm', 'square centemeters'),
    ('sq m', 'square meters'),
    ('sq km', 'square kilometers'),
    ('sq in', 'square inches'),
    ('sq ft', 'square feet'),
    ('sq yd', 'square yards'),
    ('acre', 'acres'),
    ('cu in', 'cubic inches'),
    ('cu ft', 'cubic feet'),
    ('cu yd', 'cubic yard'),
    ('acre ft', 'acre foot'),
    ('tsp', 'teaspoon'),
    ('tbsp', 'tablespoon'),
    ('fl oz', 'fluid ounces'),
    ('cp', 'cup'),
    ('US', 'US Clothing Size'),
    ('EU', 'European Clothing Size'),
    ('UK', 'British Clothing Size'),
)